version: 2.1

jobs:
  apk:
    description: "Run Android build for Flutter"
    docker:
      - image: cirrusci/flutter:1.22.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: flutter pub get
      - run:
          name: Build
          command: flutter build apk
  lint:
    description: "Run static analysis for Flutter"
    docker:
      - image: cirrusci/flutter:1.22.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: flutter pub get
      - run:
          name: Analyze code
          command: flutter analyze lib
  test:
    description: "Run tests for Flutter"
    docker:
      - image: cirrusci/flutter:1.22.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: flutter pub get
      - run:
          name: Run tests
          command: flutter test

workflows:
  build:
    jobs:
      - apk
      - lint
      - test
